import Head from "next/head";
import Layout from "@/components/Layout";
import Image from "next/image";
import profilePic from "../../public/images/profile/developer-pic-4.svg";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import HireMe from "@/components/HireMe";
import Skills from "@/components/Skills";

export default function Home() {
  return (
    <>
      <Head>
        <title>Portfolio - Ravi Sharma</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Crafting Seamless User Experience!"
                className="!text-5xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                As a proficient UI Developer, my commitment lies in transforming
                ideas into innovative web applications. Dive into my recent
                projects and articles, highlighting my expertise in React.js and
                web development.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/dummy.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2 px-6 rounded-lg text-lg hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark"
                  download={true}
                >
                  Resume
                  <LinkArrow className={"w-6 ml-1"} />
                </Link>
                <Link
                  href="mailto:ravisharma50063@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg capitalize text-dark p-2 px-6 rounded-lg hover:bg-light hover:text-dark border-2 hover:border-dark"
                >
                  Contact
                </Link>
              </div>
            </div>

            <div className="w-1/2 mr-10">
              <Image
                src={profilePic}
                alt="RaviSharma"
                className="w-full h-auto"
              />
            </div>
          </div>
        </Layout>
        <HireMe />
      </main>
      {/* <Skills /> */}
    </>
  );
}
